[package]
name = "protocol"
version = "0.0.1"
edition = "2021"
resolver = "2"

[dependencies]
prost = "=0.9"
prost-types = "=0.9"
thiserror = "=1"
tonic = "=0.6"
tonic-types = "=0.4"

[build-dependencies]
tonic-build = "=0.6"
