[package]
name = "broker"
version = "0.0.1"
edition = "2021"
resolver = "2"

[dependencies]
protocol = { path = "../protocol" }

async-stream = "=0.3"
thiserror = "=1"
tokio = { version = "=1", features = ["full"] }
tokio-stream = "=0.1"
tonic = "=0.6"
tracing = "=0.1"
tracing-subscriber = "=0.3"
